### ISSUE TITLE
syp on index fails due to doi in url error

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#1525]
In prep for release tomorrow I moved SYP from sneakpeak to https://dev.shareyourpaper.org/. 

However, now, entering a DOI causes an error:

```
Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'https://10.0.61.34/hebruniocollannu.89.2018.0221' cannot be created in a document with origin 'https://dev.shareyourpaper.org' and URL 'https://dev.shareyourpaper.org/'.
    at HTMLAnchorElement.availability (https://dev.shareyourpaper.org/static/shareyourpaper.js:730:24)
    at HTMLDivElement.dispatch (https://dev.shareyourpaper.org/static/bundled_5cca8c35b8c7f5dc0e8c39356b338a07.min.js:2:23401)
    at HTMLDivElement.y.handle (https://dev.shareyourpaper.org/static/bundled_5cca8c35b8c7f5dc0e8c39356b338a07.min.js:2:20114)
availability @ shareyourpaper.js:730
dispatch @ bundled_5cca8c35b8c7f5dc0e8c39356b338a07.min.js:2
y.handle @ bundled_5cca8c35b8c7f5dc0e8c39356b338a07.min.js:2
```

This causes the doi to not get searched, the example doesn't work.

However, direct DOI links do still work: https://dev.shareyourpaper.org/10.1126/scitranslmed.3008973

Please make sure these three things work :)

**Comment by markmacgillivray** [comment]
OK it seems to be fixed on dev now, have a look and close if you are happy
